import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import AuthSession from './session';
import Nav from '@/components/nav'
import Visit from '@/components/etc/visit'
config.autoAddCss = false;

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '은주의 게시판',
  description: 'Generated by create next app',
  icons : {
    icon : '/favicon.ico'
  }
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthSession>
          <Visit />
          <Nav />
          {children}
        </AuthSession>
      </body>
    </html>
  )
}
