import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Login from '@/components/login'
import {getServerSession} from 'next-auth';
import { authOptions } from './api/auth/[...nextauth]/route'
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false;

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '은주의 게시판',
  description: 'Generated by create next app',
  icons : {
    icon : '/favicon.ico'
  }
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

    const session = await getServerSession(authOptions)
    console.log(session)

  return (
    <html lang="en">
      <body className={inter.className}>
        <Login session={session} />
        {children}
      </body>
    </html>
  )
}
